export const GOOGLE_FONTS_LIST = [
  "Abel", "Abril Fatface", "Alata", "Alegreya", "Alegreya Sans", "Alfa Slab One", 
  "Alice", "Amatic SC", "Anonymous Pro", "Anton", "Archivo", "Archivo Black", 
  "Archivo Narrow", "Arimo", "Arizonia", "Arvo", "Asap", "Asap Condensed", 
  "Assistant", "Barlow", "Barlow Condensed", "Barlow Semi Condensed", "Bebas Neue", 
  "BioRhyme", "Bitter", "Bree Serif", "Bricolage Grotesque", "Bungee", "Cabin", 
  "Cairo", "Cantarell", "Cardo", "Catamaran", "Caveat", "Caveat Brush", "Changa", 
  "Chivo", "Cinzel", "Cinzel Decorative", "Comfortaa", "Concert One", "Cormorant", 
  "Cormorant Garamond", "Cormorant Infant", "Cormorant SC", "Cormorant Unicase", 
  "Courgette", "Courier Prime", "Crete Round", "Crimson Text", "Cuprum", 
  "Dancing Script", "Didact Gothic", "DM Mono", "DM Sans", "DM Serif Display", 
  "DM Serif Text", "Domine", "Dosis", "EB Garamond", "El Messiri", "Exo", 
  "Exo 2", "Fira Code", "Fira Sans", "Fira Sans Condensed", "Fjalla One", 
  "Francois One", "Fredoka", "Garamond", "Geist", "Gelasio", "Georgia", 
  "Gilda Display", "Gloria Hallelujah", "Gochi Hand", "Great Vibes", "Hammersmith One", 
  "Heebo", "Hind", "IBM Plex Mono", "IBM Plex Sans", "IBM Plex Serif", "Imprima", 
  "Inconsolata", "Indie Flower", "Inika", "Inter", "Istok Web", "JetBrains Mono", 
  "Josefin Sans", "Jost", "Jua", "Julius Sans One", "Kalam", "Kameron", 
  "Kanit", "Karla", "Kaushan Script", "Lalezar", "Lato", "League Script", 
  "League Spartan", "Lexend", "Lexend Deca", "Lexend Giga", "Lexend Mega", 
  "Lexend Peta", "Lexend Sans", "Lexend Tera", "Lexend Zetta", "Libre Baskerville", 
  "Libre Caslon Text", "Libre Franklin", "Lilita One", "Literata", "Lobster", 
  "Lora", "Lustria", "M PLUS 1p", "M PLUS Rounded 1c", "Mada", "Manrope", 
  "Martel", "Martel Sans", "Maven Pro", "Merriweather", "Merriweather Sans", 
  "Metrophobic", "Michroma", "Monoton", "Montserrat", "Montserrat Alternates", 
  "Montserrat Subrayada", "Mukta", "Nanum Gothic", "Nanum Myeongjo", "Neuton", 
  "News Cycle", "Nobile", "Noticia Text", "Noto Sans", "Noto Sans Display", 
  "Noto Sans Mono", "Noto Serif", "Nunito", "Old Standard TT", "Oleo Script", 
  "Open Sans", "Oswald", "Outfit", "Overpass", "Overpass Mono", "Oxygen", 
  "Oxygen Mono", "Pacifico", "Parisienne", "Pathway Gothic One", "Paytone One", 
  "Permanent Marker", "Philosopher", "Play", "Playfair", "Playfair Display", 
  "Plus Jakarta Sans", "Poiret One", "Poppins", "Prata", "Press Start 2P", 
  "Prompt", "PT Mono", "PT Sans", "PT Sans Narrow", "PT Serif", "Public Sans", 
  "Quattrocento", "Quattrocento Sans", "Quicksand", "Raleway", "Red Hat Display", 
  "Red Hat Text", "Reenie Beanie", "Righteous", "Roboto", "Roboto Mono", 
  "Rokkitt", "Ropa Sans", "Rubik", "Rubik Mono One", "Sacramento", "Saira", 
  "Saira Condensed", "Saira Semi Condensed", "Satisfy", "Secular One", "Sen", 
  "Share Tech", "Share Tech Mono", "Signika", "Sintony", "Source Code Pro", 
  "Source Sans 3", "Source Sans Pro", "Source Serif 4", "Source Serif Pro", 
  "Space Grotesk", "Space Mono", "Special Elite", "Spectral", "Suez One", 
  "Syncopate", "Tangerine", "Taviraj", "Teko", "Tenor Sans", "Tinos", 
  "Titan One", "Titillium Web", "Trirong", "Ubuntu", "Unica One", "Urbanist", 
  "Varela", "Varela Round", "Vesper Libre", "VT323", "Work Sans", "Yanone Kaffeesatz", 
  "Yantramanav", "Yellowtail", "Yeseva One", "Zilla Slab"
];
